### ISSUE TITLE
Several training issues in the current version

### ISSUE THREAD

**Issue by jungokasai** [CharizardAcademy/convtransformer#1]
I'm running into several issues in running the current version. Could you confirm that you can run training without an error? It looks like that the current version is missing options and has a syntax error. This doesn't seem like an issue with my environment. First, I found a syntax error
https://github.com/CharizardAcademy/convtransformer/blob/master/convtransformer/fairseq/models/transformer.py#L941

Even after fixing this, I got the following error with an options: 

```File "/private/home/jkasai/.conda/envs/my_pytorch_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/private/home/jkasai/projects/convtransformer/convtransformer/fairseq/models/transformer.py", line 1343, in forward
    if self.enable_pooling:
  File "/private/home/jkasai/.conda/envs/my_pytorch_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'ConvTransformerEncoderLayer' object has no attribute 'enable_pooling'`
```

**Comment by CharizardAcademy** [comment]
thanks for your feedback. We have removed some errors in the code and updated onto the repo. Pls try our latest version

**Comment by jungokasai** [comment]
Thank you! I was able to run it.

**Comment by CharizardAcademy** [comment]
issue closed
